name       : perl-data-uniqid
version    : 0.12
release    : 3
source     :
    - http://search.cpan.org/CPAN/authors/id/M/MW/MWX/Data-Uniqid-0.12.tar.gz : b6919ba49b9fe98bfdf3e8accae7b9b7f78dc9e71ebbd0b7fef7a45d99324ccb
license    : Artistic-2.0
component  : programming.perl
summary    : Perl extension for simple generation of unique IDs
description: |
    Data::Uniqid provides three simple routines for generating unique ids.
    These ids are coded with a Base62 systen to make them short and handy
    (e.g. to use it as part of a URL).
builddeps  :
    - perl
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
